### ISSUE TITLE
insert GIPHY API Attribution "Powered By GIPHY"

### ISSUE THREAD

**Issue by ilmanzo** [henrikac/lib-giphy#6]
Giphy developer section says:

"We require all apps that use GIPHY API to conspicuously display "Powered By GIPHY" attribution marks where the API is utilized (see SDK attribution guide [here](https://developers.giphy.com/docs/sdk#design-guidelines)). You can find approved official logo marks [here](http://giphymedia.s3.amazonaws.com/giphy-attribution-marks.zip)."

**Comment by henrikac** [comment]
As I understand this it is only for apps that actively use the API? And since this is just a wrapper library it is not required?

**Comment by ilmanzo** [comment]
I'm not so sure... At the end, you are the user of the API ; another app that requires this nice library, would only call its methods and never knows about API Attribution requirement. So I'd play safe and put a simple "Powered By GIPHY" with a link in the readme.md ; just my 2 cents

**Comment by henrikac** [comment]
I see, good point.
I have added the "we require ... POWERED BY ... " quote + link to the README :)
